<?php

namespace AppBundle\Repository;

/**
 * AutoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutoRepository extends \Doctrine\ORM\EntityRepository
{

  public function getAutosByBusqueda($destino, $fecha_inicio, $fecha_fin) {
    $em = $this->getEntityManager();
    $qb = $em->createQueryBuilder();

    $qb->select('a')
      ->from('AppBundle:Auto', 'a')
      ->innerJoin('a.ubicacion', 'u')
      ->where('u.id = :destino');

    $qb->setParameter('destino', $destino);

    return $qb->getQuery()->getResult();
  }

}
