<?php

namespace AppBundle\Repository;

/**
 * ServicioReservaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicioReservaRepository extends \Doctrine\ORM\EntityRepository
{
}
