<?php

namespace AppBundle\Repository;

/**
 * VueloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VueloRepository extends \Doctrine\ORM\EntityRepository
{

  public function getVuelosByBusqueda($origen, $destino, $fecha, $cant_personas) {
    return array(2);
  }

}
